# Generated by Django 3.1.2 on 2020-10-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0003_todo_isdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exer_title', models.CharField(max_length=100)),
                ('exer_time', models.CharField(max_length=100)),
            ],
        ),
    ]
