# Generated by Django 3.1.2 on 2020-10-20 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0007_auto_20201019_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exer_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='nickname',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
