# Generated by Django 3.1.2 on 2020-10-20 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0008_auto_20201020_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exer_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
